### ISSUE TITLE
Code is horrible, sorry

### ISSUE THREAD

**Issue by NovalineDev** [Ishantij/Ishans-key-system#1]
Please delete this repo before new people think this is the way to actually code a keysystem, we don't need people coding like this.

**Comment by piotr25691** [comment]
I agree.
There are the following issues:
- extremely big up-to-15-line gaps for no reason
- clusterfuck of nested if else statements
- open source licensing this bullshit
etc.

Please delete this shit.

**Comment by Ishantij** [comment]
> 

took your advice and remade it
